from routers.login import login_router
from routers.dashboard import dashboard_router
from routers.profiles import profile_router
from routers.category import category_router
from routers.banners import banner_router
from routers.ads import ads_router
from routers.posts import posts_router
from routers.popup import popup_router
from routers.inbox import inbox_router
from routers.certificate import certificate_router
from routers.promocode import promocode_router
from routers.users import users_router
from routers.push import push_router
from routers.constants import constants_router
from routers.interests import interest_router
from routers.card import card_router
from routers.ticket import ticket_router