from routers.authentication import authentication_router
from routers.interest import interest_router
from routers.home import home_router
from routers.profile import profile_router
from routers.category import category_router
from routers.answer import answers_router
from routers.card import card_router
from routers.constant import constant_router
from routers.search import search_router
from routers.ticket import ticket_router
from routers.click_view import view_count_router
from routers.users import users_router